from models.model import Model
from tensorflow.keras import Sequential, layers, models
from tensorflow.keras.layers.experimental.preprocessing import Rescaling
from tensorflow.keras.optimizers import RMSprop, Adam
from tensorflow.keras.models import load_model
import numpy as np

class RandomModel(Model):
    def _define_model(self, input_shape, categories_count):
        # Your code goes here
        # you have to initialize self.model to a keras model
        # very similar to transfered_model.py, the only difference is that you should randomize the weights
        # load your basic model with keras's load_model function
        # freeze the weights of the loaded model to make sure the training doesn't affect them
        # (check the number of total params, trainable params and non-trainable params in your summary generated by train_transfer.py)
        # randomize the weights of the loaded model, possibly by using _randomize_layers
        # use this model by removing the last layer, adding dense layers and an output layer
        
        # Load the same basic model architecture
        basic = load_model('../src/results/basic_model_20_epochs_timestamp_1770866701.keras')
        
        # Randomize the weights
        basic = self._randomize_layers(basic)
        
        # Remove softmax layer
        basic = models.Model(
            inputs=basic.input,
            outputs=basic.layers[-2].output
        )
        
        basic.trainable = True
        
        # Build new model
        model = Sequential()
        model.add(basic)
        
        # Add new trainable layers
        model.add(layers.Dense(64, activation='relu'))
        model.add(layers.Dropout(0.5))
        model.add(layers.Dense(categories_count, activation='softmax'))
        
        self.model = model
    
    def _compile_model(self):
        # Your code goes here
        self.model.compile(
            optimizer=RMSprop(learning_rate=0.001),
            loss='categorical_crossentropy',
            metrics=['accuracy']
        )

    @staticmethod
    def _randomize_layers(model):
        for layer in model.layers:
            if hasattr(layer, 'get_weights') and layer.get_weights():
                # Get current weights shape
                weights = layer.get_weights()
                new_weights = []
                for w in weights:
                    # Create random weights with same shape, small random values
                    random_w = np.random.randn(*w.shape) * 0.01
                    new_weights.append(random_w)
                layer.set_weights(new_weights)
        return model