from models.model import Model
from tensorflow.keras import Sequential, layers, models
from tensorflow.keras.layers.experimental.preprocessing import Rescaling
from tensorflow.keras.optimizers import RMSprop, Adam
from tensorflow.keras.models import load_model

class TransferedModel(Model):
    def _define_model(self, input_shape, categories_count):
        # Your code goes here
        # you have to initialize self.model to a keras model
        # load your basic model with keras's load_model function
        # freeze the weights of the loaded model to make sure the training doesn't affect them
        # (check the number of total params, trainable params and non-trainable params in your summary generated by train_transfer.py)
        # use this model by removing the last layer, adding dense layers and an output layer

        basic = load_model('../src/results/basic_model_20_epochs_timestamp_1770866701.keras')
        
        # Remove softmax layer
        basic = models.Model(
            inputs = basic.input,
            outputs = basic.layers[-2].output
        )

        # Freeze the weights
        basic.trainable = False

        model = Sequential()
        model.add(basic)

        # Add new trainable layer
        model.add(layers.Dense(64, activation='relu'))  # New dense layer
        model.add(layers.Dropout(0.5))
        
        # Output layer for new categories count
        model.add(layers.Dense(categories_count, activation='softmax'))
        
        self.model = model
    
    def _compile_model(self):
        # Your code goes here
        # you have to compile the keras model, similar to the example in the writeup
        self.model.compile(
            optimizer=RMSprop(learning_rate=0.001),
            loss='categorical_crossentropy',
            metrics=['accuracy']
        )
